export const SET_LOADING = 'set/loading'
export const SET_ERROR = 'set/error'
export const FECTH_PRODUCTS = 'products/getProducts'
export const SET_INCREMENT = 'set/increment'
export const SET_DECREMENT = 'set/decrement'